package mysqlrepo

import (
	"fmt"
	"reflect"
	"strings"

	sq "github.com/Masterminds/squirrel"
)

const FieldCreatedAt string = "CreatedAt"
const FieldUpdatedAt string = "UpdatedAt"
const FieldDeletedAt string = "DeletedAt"

// DBTableInfo .
type DBTableInfo struct {
	Table                 string
	Columns               []string //table columns involved for this struct
	InsertColumns         []string //table columns used for insert
	StructDBFields        []string //name of the variable of the struct
	StructUniqueDBFields  []string //name of the variable of the struct unique columns
	PKColumns             []string
	InsertColumnIndexes   [][]int  //the index of the tag
	SearchableColumns     []string //columns that we are performing the like query
	GeneratedColumns      []string //columns that are generated by the database
	SearchStatementFormat string
	ColumnMap             map[string]string //columns in another format
	SourceStruct          any
	CreateTime            AutoTimeField
	UpdateTime            AutoTimeField
	DeleteTime            AutoTimeField
}

func (info *DBTableInfo) CreateTimeNow() any {
	return TimeNow(info.CreateTime.TimeType)
}
func (info *DBTableInfo) CreateTimeEmpty() any {
	return TimeEmpty(info.CreateTime.TimeType)
}
func (info *DBTableInfo) CreateTimeKey() string {
	return info.CreateTime.Key
}

func (info *DBTableInfo) UpdateTimeNow() any {
	return TimeNow(info.UpdateTime.TimeType)
}
func (info *DBTableInfo) UpdateTimeEmpty() any {
	return TimeEmpty(info.UpdateTime.TimeType)
}
func (info *DBTableInfo) UpdateTimeKey() string {
	return info.UpdateTime.Key
}

func (info *DBTableInfo) DeleteTimeNow() any {
	return TimeNow(info.DeleteTime.TimeType)
}
func (info *DBTableInfo) DeleteTimeEmpty() any {
	return TimeEmpty(info.DeleteTime.TimeType)
}
func (info *DBTableInfo) DeleteTimeKey() string {
	return info.DeleteTime.Key
}

type AutoTimeField struct {
	Key      string
	TimeType TimeType
}

// PrepareDBTableInfo scans a struct and extract data into different lists based on struct tags db
// dbfield is a custom tag, supporting
// ai(auto increment)
// pk(primary key)
// unique(unique column)
// search(concated into a like query)
func PrepareDBTableInfo(table string, sourceStruct any) *DBTableInfo {
	//Init lists
	r := DBTableInfo{
		Table:                table,
		Columns:              make([]string, 0),
		InsertColumns:        make([]string, 0),
		StructDBFields:       make([]string, 0),
		StructUniqueDBFields: make([]string, 0),
		PKColumns:            make([]string, 0),
		InsertColumnIndexes:  make([][]int, 0),
		SearchableColumns:    make([]string, 0),
		ColumnMap:            make(map[string]string),
		SourceStruct:         sourceStruct,
	}
	scanStruct(sourceStruct, &r)

	if len(r.SearchableColumns) > 0 {
		r.SearchStatementFormat = StmtConcatWS(" ", r.SearchableColumns...)
	}

	return &r
}

func scanStruct(s any, r *DBTableInfo) {
	if s == nil {
		return
	}
	t := reflect.TypeOf(s)
	v := reflect.ValueOf(s)

	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	numFields := t.NumField()

	//Loop the struct and get their fields
	for i := 0; i < numFields; i++ {
		fieldDetail := t.Field(i)
		switch fieldDetail.Type.Kind() {
		case reflect.Struct:

			if fieldDetail.Anonymous {
				scanStruct(v.Field(i).Interface(), r)
			} else {
				checkAndAppendToColumns(fieldDetail, r)
			}
		default:
			checkAndAppendToColumns(fieldDetail, r)
		}
	}
}

func checkAndAppendToColumns(fieldDetail reflect.StructField, r *DBTableInfo) {
	if field := fieldDetail.Tag.Get("db"); field != "" {
		dbField := fieldDetail.Tag.Get("dbfield")

		table := r.Table
		if tabletag, e := fieldDetail.Tag.Lookup("table"); e {
			table = tabletag
		}

		dbFieldMap := ToDBFieldMap(dbField)

		if IsDBField(dbFieldMap, "sub") {
			//we don't do anything for subqueries data, non of the below should be processed
			return
		}

		if !IsDBField(dbFieldMap, "ai") && !IsDBField(dbFieldMap, "generated") {
			r.StructDBFields = append(r.StructDBFields, fieldDetail.Name)
			r.InsertColumns = append(r.InsertColumns, field)
			r.InsertColumnIndexes = append(r.InsertColumnIndexes, fieldDetail.Index)
		}

		if IsDBField(dbFieldMap, "pk") {
			r.PKColumns = append(r.PKColumns, field)
		}
		if IsDBField(dbFieldMap, "unique") {
			r.StructUniqueDBFields = append(r.StructUniqueDBFields, fieldDetail.Name)
		}
		if IsDBField(dbFieldMap, "search") {
			searchableField := field
			if table != "" {
				searchableField = fmt.Sprintf("%s.%s", table, field)
			}
			r.SearchableColumns = append(r.SearchableColumns, searchableField)
		}

		if IsDBField(dbFieldMap, "generated") {
			r.GeneratedColumns = append(r.GeneratedColumns, fieldDetail.Name)
		}

		selectField := field
		if table != "" {
			selectField = fmt.Sprintf("%s.%s", table, field)
		}

		if IsDBField(dbFieldMap, "alias") {
			alistmt, _, _ := sq.Alias(sq.Expr(dbFieldMap["alias"]), field).ToSql()
			selectField = alistmt
		}

		switch fieldDetail.Name {
		case FieldCreatedAt: //turn type into TimeType
			r.CreateTime = AutoTimeField{
				Key:      field,
				TimeType: ToTimeType(fieldDetail.Type),
			}
		case FieldUpdatedAt:
			r.UpdateTime = AutoTimeField{
				Key:      field,
				TimeType: ToTimeType(fieldDetail.Type),
			}
		case FieldDeletedAt:
			r.DeleteTime = AutoTimeField{
				Key:      field,
				TimeType: ToTimeType(fieldDetail.Type),
			}
		}

		r.Columns = append(r.Columns, selectField)
		r.ColumnMap[field] = table
	}
}

// IsDBField .
func IsDBField(tagMap map[string]string, prop string) bool {
	if tagMap == nil {
		return false
	}
	_, e := tagMap[prop]
	return e
}

func ToDBFieldMap(tagstr string) map[string]string {
	if tagstr == "" {
		return nil
	}

	result := make(map[string]string)
	fields := strings.Split(tagstr, ",")
	for _, f := range fields {
		k, v := head(f, "=")
		result[k] = v
	}
	return result
}

func FilterKeys(source map[string]any, reserveKeys []string) map[string]any {
	result := make(map[string]any)
	for _, key := range reserveKeys {
		if val, ok := source[key]; ok {
			result[key] = val
		}
	}
	return result
}

func head(str, sep string) (head string, tail string) {
	idx := strings.Index(str, sep)
	if idx < 0 {
		return str, ""
	}
	return str[:idx], str[idx+len(sep):]
}
